"""Static game data: villagers, dialogue, palettes and named places.
Shared by generate_assets.py (for sprites/portraits) and the game itself."""

S1 = (244, 208, 170)
S2 = (226, 176, 130)
S3 = (186, 128, 88)
S4 = (132, 88, 60)

HERO = dict(skin=S1, hair=(112, 70, 42), style="short", shirt=(72, 150, 92),
            pants=(112, 92, 72), shoe=(70, 46, 34), scarf=(206, 62, 62),
            cape=(58, 96, 168), belt=True)

# home = tile where the villager lives / wanders around
NPCS = [
    dict(id="elder", name="Elder Maren", role="Village Elder", home=(44, 46), radius=3, speed=18,
         pal=dict(skin=S2, hair=(228, 228, 232), style="bald", beard=True,
                  shirt=(72, 92, 168), pants=(70, 70, 100), robe=True, shoe=(70, 50, 40)),
         intro=["Ah, a new face! Welcome to Hearthmoor, traveler.",
                "Our village has stood between the Whisperwood and Reedwater Pond for three hundred years.",
                "Wander wherever you like. The roads are safe and the folk are friendly. Say hello to everyone; it's good luck."],
         chatter=[["The old shrine in the north grove hums on quiet nights. Some say it remembers the very first villagers."],
                  ["Follow the east road past the plaza and you'll reach the hunter's camp. Rook doesn't say much, but he's kind."],
                  ["Mind the chickens. They have declared the plaza their territory."]],
         all_met=["You've greeted every soul in Hearthmoor!",
                  "The whole village is talking about the traveler who took the time to listen. Consider yourself one of us.",
                  "The Whisperwood is vast and the world is wider still. Go and see it, and come back with stories."]),
    dict(id="rosalind", name="Rosalind", role="Innkeeper", home=(31, 45), radius=3, speed=20,
         pal=dict(skin=S1, hair=(176, 72, 40), style="bun", shirt=(196, 78, 78),
                  pants=(96, 64, 52), apron=(246, 242, 232)),
         intro=["Welcome to the Sleeping Fox Inn! Best stew this side of the Whisperwood.",
                "Every bed is full, I'm afraid. A certain bard has been 'resting his voice' in my loft for a week."],
         chatter=[["The secret to my stew? Patience, thyme, and never letting Tobias near the pot."],
                  ["If you're hungry, Pip's bakery is just up the road. Tell him I sent you. He'll charge you less."],
                  ["Lark plays every evening in the plaza. Off-key, but with feeling."]]),
    dict(id="tobias", name="Tobias", role="Shopkeeper", home=(62, 45), radius=3, speed=20,
         pal=dict(skin=S2, hair=(96, 64, 40), style="short", hat="cap", hatc=(60, 124, 92),
                  shirt=(214, 184, 100), pants=(86, 70, 60), apron=(156, 116, 72)),
         intro=["Step right up! Rope, lanterns, honey, buttons, one slightly haunted teapot...",
                "Sadly I'm between shipments, so the shelves are empty. Come back after the next caravan!"],
         chatter=[["Business has been slow. Everyone just wants to talk to the new traveler instead of buying things."],
                  ["I once sold a boot to a man with three feet. Longest conversation of my career."],
                  ["Between us, the teapot isn't haunted. It just whistles when nobody's looking."]]),
    dict(id="bram", name="Bram", role="Blacksmith", home=(60, 57), radius=3, speed=18,
         pal=dict(skin=S3, hair=(58, 40, 30), style="braid", shirt=(120, 120, 134),
                  pants=(72, 68, 74), apron=(70, 62, 68), armor=True),
         intro=["Mind the sparks! Bram's the name, and iron is my game.",
                "Plows, hinges, horseshoes... Nothing fancy lately. The village is peaceful, and I'm not complaining."],
         chatter=[["The trick to good steel? Listen to it. Every hammer-strike tells you what it wants to be."],
                  ["Tilly keeps sneaking in to ring my anvil. I pretend not to notice."],
                  ["Forging a sword is easy. Forging a reason to need one is the hard part."]]),
    dict(id="pip", name="Pip", role="Baker", home=(52, 46), radius=2, speed=18,
         pal=dict(skin=S1, hair=(204, 150, 84), style="short", hat="chef", hatc=(250, 250, 246),
                  shirt=(122, 152, 196), pants=(98, 84, 78), apron=(250, 250, 244)),
         intro=["Fresh bread! Hot out of the oven! Well, an hour ago. But still warm in spirit!",
                "Try a roll? ...Oh. You can't, I haven't baked for the day. Come back at sunrise!"],
         chatter=[["I get up at four every morning to knead the dough. The roosters hate me for it."],
                  ["Rosalind says my honey buns are better than her stew. Don't tell her I told you."],
                  ["The secret ingredient is love. And butter. Mostly butter."]]),
    dict(id="gil", name="Farmer Gil", role="Farmer", home=(29, 67), radius=4, speed=18,
         pal=dict(skin=S2, hair=(150, 120, 90), style="short", hat="straw", hatc=(232, 202, 112),
                  shirt=(196, 164, 112), pants=(72, 102, 152), beard=True),
         intro=["Afternoon, friend! Mind the cabbages.",
                "Best harvest in years. Wheat, carrots, pumpkins... even the weeds are thriving."],
         chatter=[["That scarecrow over there? I swear it turns to watch me work."],
                  ["Crows don't fear it anymore. Last week one sat on its head and had lunch."],
                  ["Nothing beats the smell of fresh soil after rain."]]),
    dict(id="odell", name="Old Odell", role="Fisherman", home=(66, 66), radius=1, speed=12,
         pal=dict(skin=S3, hair=(150, 150, 160), style="short", hat="cap", hatc=(228, 186, 58),
                  shirt=(232, 192, 62), pants=(70, 86, 108), robe=True, beard=True),
         intro=["Shhh... you'll scare the fish.",
                "Been sitting on this dock forty years. Caught one boot, two eels, and a lot of peace and quiet."],
         chatter=[["There's a big old carp in this pond. Name's Gerald. We have an understanding."],
                  ["Patience, young one. The pond gives to those who wait."],
                  ["Moonlake, up north-east, is where the really big ones hide. Only the brave dare cast there."]]),
    dict(id="tilly", name="Tilly", role="Village Kid", home=(70, 47), radius=9, speed=44,
         pal=dict(skin=S2, hair=(244, 200, 84), style="pigtails", shirt=(244, 150, 62),
                  pants=(82, 112, 172)),
         intro=["Tag! You're it! ...Wait, you're new. Tag anyway!",
                "I'm Tilly! I know everything about everything in Hearthmoor. Ask me anything!"],
         chatter=[["I counted every chicken in the village. There are four. Or five. They won't hold still."],
                  ["Bram let me hit the anvil ONCE. It went BONG. Best day ever."],
                  ["Wren the herbalist is a witch. She says she's not. But she totally is."],
                  ["Race you to the pond! ...Wait, I can't. Mama says I have to finish my turnips."]]),
    dict(id="aldric", name="Sir Aldric", role="Village Guard", home=(48, 30), radius=4, speed=18,
         pal=dict(skin=S3, hair=(80, 56, 40), style="short", hat="helmet", hatc=(170, 176, 192),
                  shirt=(150, 158, 176), pants=(84, 86, 108), armor=True),
         intro=["Halt! ...Oh. You're fine. Carry on, traveler.",
                "I guard the north road. Not much to guard against, truth be told. Last bandit was a raccoon."],
         chatter=[["The road north ends at the Whispering Shrine. Peaceful place. A little too quiet at night."],
                  ["Training never stops. I've been practicing my stern look. How is it?"],
                  ["If you hear strange humming in the forest, it's probably just the shrine. Probably."]]),
    dict(id="rook", name="Rook", role="Hunter", home=(79, 37), radius=3, speed=20,
         pal=dict(skin=S4, hair=(30, 26, 30), style="short", hat="hood", hatc=(72, 112, 72),
                  shirt=(86, 106, 62), pants=(94, 72, 52), scarf=(190, 160, 80)),
         intro=["...", "You walk loud for a traveler. But you walked here, so you're alright.",
                "Camp's open to anyone. Fire's warm. That's all I've got."],
         chatter=[["Deer tracks near the lake today. Big ones."],
                  ["The forest speaks if you stop moving. Try it sometime."],
                  ["Don't wander the Whisperwood at night without a lantern. Or a good reason."]]),
    dict(id="wren", name="Sage Wren", role="Herbalist", home=(19, 45), radius=3, speed=18,
         pal=dict(skin=S1, hair=(150, 108, 204), style="long", hat="witch", hatc=(92, 60, 134),
                  shirt=(116, 82, 156), pants=(70, 50, 90), robe=True),
         intro=["Oh! A visitor. Do mind the foxglove, dear. Pretty, but quite poisonous.",
                "I'm Wren. I brew remedies, teas, and the occasional tonic that makes your hair stand up."],
         chatter=[["Tilly says I'm a witch. I'm a botanist with excellent hats."],
                  ["Chamomile for sleep, mint for the stomach, and sage for... well, wisdom. Mostly."],
                  ["The shrine up north glows when the moon is full. The plants lean towards it. Fascinating."]]),
    dict(id="lark", name="Lark", role="Travelling Bard", home=(44, 50), radius=5, speed=22,
         pal=dict(skin=S3, hair=(34, 32, 44), style="long", hat="feather", hatc=(206, 62, 96),
                  shirt=(66, 156, 164), pants=(206, 164, 64), scarf=(240, 220, 120)),
         intro=["Greetings, friend! Lark the bard, at your service. Care for a song?",
                "'Oh, the road is long and the boots are worn, but the stew is hot and the day is born!' Hm. Needs work."],
         chatter=[["I'm composing a ballad about this village. So far it's just the word 'cabbage' rhymed with 'baggage'."],
                  ["Rosalind says I'm out of tune. I say I'm ahead of my time."],
                  ["Every village has a story. Hearthmoor's is still being written. Perhaps by you."]]),
]

# Named areas (tile rectangles x0, y0, x1, y1) for the location banner
PLACES = [
    ("Hearthmoor Plaza", (40, 42, 57, 54)),
    ("Gil's Farm", (21, 61, 37, 75)),
    ("Reedwater Pond", (59, 58, 77, 74)),
    ("Hunter's Camp", (72, 30, 86, 43)),
    ("Goddess Sanctuary", (38, 3, 59, 13)),
    ("Whispering Shrine", (41, 13, 56, 22)),
    ("Moonlake", (68, 6, 92, 30)),
    ("The Hollow Gate", (43, 82, 54, 93)),
]


# Character art: RPG Maker VX Ace style sheets in assets/rpgmaker/ (8 characters per sheet,
# numbered left-to-right, top-to-bottom). (sheet, index)
HERO_SPRITE = ("Actor1", 0)
SPRITES = {
    "elder": ("Actor1", 7), "rosalind": ("Actor1", 5), "tobias": ("Actor3", 0), "bram": ("Actor1", 6),
    "pip": ("Actor2", 3), "gil": ("Actor1", 2), "odell": ("Actor2", 6), "tilly": ("Actor2", 1),
    "aldric": ("Actor3", 6), "rook": ("Actor3", 2), "wren": ("Actor2", 7), "lark": ("Actor2", 4),
}
